[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/dev/stdout
logfile_maxbytes=0

[program:indictrans2]
command=/app/venv/bin/uvicorn indictrans2_service:app --host 0.0.0.0 --port 5102
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
